
// Array of 100 memory texts for the memory pages
export const memoryTexts = [
  "15 de janeiro de 2025 - Tu e eu no jogo do Palmeiras em Barueriii",
  "29 de junho - Eu e tu assistindo jogos no nosso primeiro interusppp",
  "3 de julho de 2022 - Eu, tu, tua mãe e tua irmã. Acho que foi quando eu conehci elasss, no reminho",
  "15 de julho de 2022 - Eu, tu e meus paisss. Foi quando você conheceu eles?",
  "2 de agosto de 2022 - Foi quando você conheceu minha prima, e sua prima kkkkkk",
  "4 de agosto de 2022 - Eu e tu em algum lugar hehe",
  "7 de agosto de 2022 - Eu e tu no hard rock de Ribeirão",
  "14 de agosto de 2022 - Tu e eu no carroooo",
  "Não sei de quando - Eu e tu comendo japaaaaa",
  "24 de setembro de 2022 - Eu e tu ostentando as aliança",
  "30 de setembro de 2022 - Eu e tu dando uma linguadinha...",
  "28 de outubro de 2022 - Eu, tu e primo de vestido!!!",
  "Carnafarra X - Eu e tu lindos e gostosos",
  "Num seeeiii - Eu tentando engolir tu que tá linda",
  "1 de janeiro de 2025 - Tu e eu vendo os fogos de ano novoooo",
  "Carnafarra Y - Eu e tu na nossa fotinha de coraçãooooo",
  "Algum dia hehe - Tu e teu cabelo maravilhoso todo vinho potente deslumbrante",
  "Não sei também, sorry - Eu e tu por aí no mundo se amando",
  "14 de fevereiro de 2022 - Eu e tu... Provavelmente você não vai gostar dessa foto aqui, mas tive que colocar, foi um momento especial hehe",
  "18 de março de 2022 - Eu e tu no becooo, quando ainda era moda kk",
  "18 de março de 2022 - Eu e tu no beco de novooo akakakaakk. Rara imagem dos dois mostrando o piano, como diz seu pai",
  "20 de maio de 2022 - Eu e tu papando Hamburgerrrr",
  "20 de maio de 2022 - Tu e eu de mascarinhass, acho que indo ou voltando do burger kkkk",
  "23 de maio de 2022 - Eu e tu no CAM. Toma essa beijoca",
  "3 de junho de 2022 - Eu e tu no Zé do hambúrguer ebaaaa, adoro lá mo. Lindos nós dois",
  "20 de julho de 2022 - Tu e eu no elevador do meu prédio. Muito rockeiros🤟",
  "Algum dia de hamburger - Sorrisinho da gatinha de guardanapo",
  "6 de outubro de 2022 - Eu e tu no meu espelhinho, simples e queridos",
  "26 de janeiro de 2023 - Eu e tu passeandinho com o Tobby, você cuidando dele e eu cuidando de você hehe",
  "3 de abril de 2023 - Vocêzinha, princesinha, bonitinha e maluquinha",
  "19 de fevereiro de 2024 - Tu e eu no metrô do Rio. Sim, tem muitas fotos do Rio akaakaka",
  "Algum dia de nossas vidas - Eu e tu comendo foundueeeee, hiper chiques baby",
  "24 de julho de 2022 - Eu, cocolina e tu",
  "5 de agosto de 2022 - Tu e eu no Borelli akaakakkaka. Lembro que falamos disso em dias, não sabia que fazia tanto tempo mds",
  "18 de agosto de 2022 - Eu, fotógrafo apaixonado, e tu linda com o doguinho lindo do canil",
  "1 de fevereiro de 2023 - Eu e tu no meu elevador de novo, mas dessa vez chiquetosos",
  "21 de abril de 2023 - Eu e tu em aparecidaaaaaa",
  "Nós dois juntos - Eu e tu no Madero papando hehe", 
  "11 de janeiro de 2024 - Eu e tu em Juquehy ebaaaa. Gostosa você ein!!",
  "23 de janeiro de 2024 - Eu, tu e Cocolina hamburgando",
  "23 de janeiro de 2024 - Eu e tu no cão veiooooo",
  "30 de janeiro de 2024 - Eu e tu na cadimia. Raras imagens...",
  "9 de fevereiro de 2024 - Eu e tu muito fitness na época que tínhamos tempo kkkkk ",
  "14 de fevereiro de 2024 - Tu e eu em su casita. Eu entendendo nada akaakakak",
  "16 de fevereiro de 2024 - Eu e tu no becooo, amados queridos",
  "18 de fevereiro de 2024 - Tu amiguinha da natureza comigo no jardim botânico. Temos que voltar laaaa",
  "18 de fevereiro de 2024 - Eu e tu nas palmeiras do jardim botânico. Com um turista exigente de fotografo akakaka",
  "18 de fevereiro de 2024 - Eu e tu no Rio Opennnn, fala deles",
  "18 de fevereiro de 2024 - Outro ângulo de eu e tu no Rio Opennn. Pra provar que não era uma arquibancada qualquer hehe",
  "19 de fevereiro de 2024 - Eu e tu na confeitaria Colombo, ui ui ui, coisa de realeza tá?",
  "19 de fevereiro de 2024 - Tu toda linda princesa na escadaria Selaron",
  "19 de fevereiro de 2024 - Eu e tu na favela, mentira, na Selaronn",
  "19 de fevereiro de 2024 - Eu e tu de boax na praia meu amor",
  "20 de fevereiro de 2024 - Tu e eu ciclistas no Rio de Janeiro que continua lindo",
  "20 de fevereiro de 2024 - Eu e tu a papar no riooo",
  "20 de fevereiro de 2024 - Tu e eu lindicos gatitos",
  "19 de fevereiro de 2024 - Tu e eu no metrô do Rio, uma fortuna slk ",
  "20 de fevereiro de 2024 - Tu e eu na Confeitaria Colombo, fala deles",
  "20 de fevereiro de 2024 - Tu e eu papando pokeeee, pena que virou trauma kakaakak",  
  "25 de fevereiro de 2024 - Eu e tu chiquetosos na formatura da Bia",
  "25 de fevereiro de 2024 - Eu e tu com meu casaquinho porque tava com frio na festa",
  "5 de maio de 2024 - Tu se despedindo da queridinha Eco, que Deus a tenha",
  "6 de maio de 2024 - Tu posando pra fotinha que eu sai tirando até o fim da mecanica porque sou autistinha akaak",
  "17 de maio de 2024 - Tu e eu embaixo de uma árvore (não lembro onde é kkkkkk)",
  "29 de maio de 2024 - Eu, tu e a CAMzaiada no Mc do Interusp",
  "31 de maio de 2024 - Tu e eu sem luz na tenda do Interusp",
  "31 de maio de 2024 - Tu e eu com luz na tenda do Interusp",
  "22 de junho de 2024 - Tu GATA PRA KRL e eu no show da Marisa na USP uhuuuu",
  "2 de julho de 2024 - Tu, eu e Calça tirando foto pro trabalho de Atuadores kkkkkk",
  "17 de agosto de 2024 - Eu, tu e Cocolina em algum lugar",
  "20 de agosto de 2024 - Eu tirando foto de tu nanante aconchegada",
  "4 de outubro de 2024 - Eu e tu em algum chopis",
  "20 de novembro de 2024 - Tu vindo me visitar no hospital em Ribeirão. Muito perfeita!",
  "1 de janeiro de 2025 - Tu recebendo beijinho meu no primeiro dia do ano",
  "1 de março de 2025 - Tu e eu na escada rolante do shopis",
  "29 de setembro de 2024 - Tu toda coordenadora gatinha da oficina",
  "28 de outubro de 2024 - Eu experimentando blusa e tu sorrindinha princesa",
  "27 de novembro de 2024 - Tu nanante na minha kitnetzinha",
  "31 de dezembro de 2024 - Eu e tu de oclinho de ano novo hehe",
  "31 de dezembro de 2024 - Tu e eu lindos e maravilhosos na virada do ano",
  "1 de janeiro de 2025 - Eu e tu nos fogos de Juquehyyyyyyyyy uhuuuuuuuu",
  "1 de janeiro de 2025 - Eu e tu no primeiro dia do anooooo. Você toda gostosa e eu cheio das dobrinhas ja",
  "3 de janeiro de 2025 - Eu e tu no As Ilhasssssss, rango bão!",
  "3 de janeiro de 2025 - Tu e eu batendo uma tranca honesta. Provavelmente fui amassado kk",
  "6 de janeiro de 2025 - Eu e tu em Juquehy com seu cabelo lindinho lindinho vermelhinho",
  "24 de janeiro de 2025 - Tu no rancho, distraíduxa e linduxa",
  "26 de janeiro de 2025 - Eu e tu no ranchoooo. Você amou esse dog, achei fofissimo",
  "9 de fevereiro de 2025 - eu admirando tu num dia comum",
  "22 de fevereiro de 2025 - Tu e eu no Cristo Redentorrrr. Eu, com a sétima e a oitava maravilha do mundo",
  "23 de fevereiro de 2025 - Eu e tu no Rio esse anooooo",
  "1 de março de 2025 - Tu e eu na escada rolante do shopis",
  "1 de março e 2025 - Tu me beijando e eu fazendo gracinha, lero lero",
  "15 de março de 2025 - Tu nanando gotosooooo, eu vendo né ",
  "15 de março de 2025 - Eu tirando foto de tu no aniversário da Cocolina",
  "9 de maio de 2025 - Tu e eu comendo na Baccio hmmmm",
  "15 de junho 2022 - Acho que sou eu e tu indo para Ribeirão, ebaaaa. Primeira vez??",
  "2 de julho de 2022 - Eu cabeludo e tu linda como sempre. Não lembro onde foi akaakaka",
  "2 de julho de 2022 - Eu e tu de colares combinandinhooo. Acho que estamos na raia aakakakaak",
  "4 de julho de 2022 - Eu lambendo tu dormindo, em mi casita, na cama gigante",
  "4 de fevereiro de 2023 - Eu e tu, tatu. Não lembro onde é akakaakaks",
  "19 de dezembro de 2021 - Eu e tu no nosso primeiro encontrooooo",
  "17 de dezembro de 2021 - Eu conhecendo tuuuuuu (sonho realizado)",
  "19 de dezembro de 2021 - Tu e eu no nosso primeiro encontrooooo, lindossss",
  "26 de Janeiro de 2022 - Eu e tu numa call no disc há muuuuito tempo atrás. Estávamos no nosso web namoro hehe",
  "3 de Fevereiro de 2022 - Cari, tu e eu no cantinho. Gosto dessa foto. Estava quase me mudando e liguei pra vc e vc tava na CAM",
  "24 de abril de 2022 - Eu, tu e a Bia no Carnafarra. Não lembro se era o 1 ou 2",
  "29 de maio de 2022 - Finalmente me assumiu pro mundo, zoas kkkkkk. Amo essa fotinha",
  "25 de junho de 2022 - Não tem eu, mas tem tu e sua família linda, tive que por também ",
  "6 de julho de 2022 - Ainda bem que roubei, melhor coisa que fiz. Adoro esse efeito",
  "Não lembro quando foi - Mas eu e tu me abraçandinho por trás, amo!",
  "20 de setembro de 2022 - Eu e tu no meu elevador com as roupitchas do nosso primeiro dateeeee",
  "24 de dezembro de 2022 - Véspera de Natal, nosso primeiro Natal namorando mexmo, a curva mais perfeita da natureza na foto aí ",
  "15 de Janeiro 2023 - Eu e tu em Juquehy uhuuuuuu, passeio de barcooo, fala deles",
  "23 de abril de 2023 - Tu e eu nessa foto clássica!! Linguarudos no carnafarra",
  "13 de maio de 2023 -Eu e tu no seu niverrrrrrrrrrr, conheci sua familiaaaa",
  "Não sei quando foi esse mas amo essa foto. Eu e tu descolados",
  "12 de junho de 2022 - Eu e tu na USP de Reberão",
  "25 de dezembro de 2023 - Mais um Natal. Tu lindíssima e eu admirando muitissimo",
  "11 de maio de 2024 - Tu no ronco na call e eu te admirando hehe",
  "9 de outubro de 2024 - Novamente tu fazendo gracinha. Muito sapeca levada da breca (não consigo aprender desculpa akakaka)",
  "11 de outubro de 2024 - Eu com tu fazendo gracinha numa call",
  "12 de janeiro de 2024 - Eu carregando tu em Juquehyyyyyyyyyyy",
  "12 de janeiro de 2024 - Eu com tu dançando em Juquehyyyyyyyyyyy",
  "30 de abril de 2022 - Eu e minha frô, que também ganhou uma frôoo",
  "25 de novembro de 2024 - Tu e eu numa call. Dessa vez você não minha casa🤔",
  "16 de dezembro de 2024 - Eu flagrando tu fazendo nojeirice. Que feio!",
  "27 de dezembro de 2024 - Tu e eu numa call, você toda linda com o cabelo finalizado, que deusa mds",
  "26 de fevereiro de 2025 - Tu brava e eu sorridente sapeca",
  "8 de março - Eu e tu no niver da Thaisss",
  "1 de maio de 2025 - Foto recente de euzinho e tu nenenzinha",
  "That time we helped each other achieve a goal.",
  "When we created a memory jar to collect moments.",
  "Our first time making breakfast together.",
  "The day we found out we have the same taste in music.",
  "That time we planned our future travels.",
  "When we celebrated an unexpected win together."
];

// Export a function to get a specific memory text by index
export const getMemoryText = (index: number): string => {
  if (index >= 1 && index <= memoryTexts.length) {
    return memoryTexts[index - 1];
  }
  return "Create a special memory description here...";
};
