
// Array of 100 memory texts for the memory pages
export const memoryTexts = [
  "Our first date at that little café where we talked until closing time.",
  "The day we got caught in the rain and shared an umbrella.",
  "When we stayed up all night looking at the stars.",
  "That road trip where we got lost but discovered an amazing view.",
  "The first time you made me breakfast in bed.",
  "When we danced in the kitchen at midnight.",
  "The day we adopted our pet together.",
  "Our first awkward attempt at cooking a fancy dinner.",
  "That time we built a fort in the living room and watched movies all day.",
  "When you surprised me with tickets to my favorite band.",
  "The day we planted our garden together.",
  "Our first holiday together.",
  "The moment we realized we were in love.",
  "That hiking trip where we reached the summit together.",
  "When we made each other handmade gifts.",
  "Our first New Year's Eve kiss.",
  "The day we decided on our song.",
  "That picnic in the park where we watched clouds.",
  "When we wrote each other love letters.",
  "The first time we met each other's families.",
  "Our beach day where we collected shells.",
  "The time we stayed up talking all night.",
  "When we went ice skating and couldn't stop laughing.",
  "That farmers market morning where we bought fresh flowers.",
  "The day we made our relationship official.",
  "Our first argument and how we resolved it.",
  "When we slow-danced in the living room.",
  "The time we built snowmen together.",
  "Our spontaneous weekend getaway.",
  "When we nursed each other through being sick.",
  "The day we picked out furniture together.",
  "Our first Valentine's Day celebration.",
  "When we created our bucket list.",
  "That karaoke night where we sang duets.",
  "The morning we watched the sunrise together.",
  "Our first Christmas tree decorating.",
  "When we wrote our future plans together.",
  "The day we found 'our spot'.",
  "That time we tried a new cuisine together.",
  "When we made a scrapbook of our memories.",
  "Our birthday celebrations for each other.",
  "The day we exchanged meaningful gifts.",
  "That game night with friends where we were the perfect team.",
  "When we shared our deepest fears with each other.",
  "The first time you introduced me as your partner.",
  "Our first inside joke that still makes us laugh.",
  "The day we decided on our future home.",
  "That time we went stargazing and saw a shooting star.",
  "When we planned our dream vacation together.",
  "Our first 'I love you'.",
  "The day we started our own traditions.",
  "That concert where we danced all night.",
  "When we surprised each other with thoughtful gestures.",
  "Our first photo together that we both love.",
  "The day we talked about our future family.",
  "That time we volunteered together for a cause.",
  "When we celebrated our first milestone together.",
  "Our first disagreement that made us stronger.",
  "The day we found out we have the same favorite book.",
  "That late-night conversation about our dreams.",
  "When we shared childhood memories with each other.",
  "Our first experience trying something neither of us had done before.",
  "The day we discovered our shared passion.",
  "That time we comforted each other through tough times.",
  "When we celebrated a personal achievement together.",
  "Our first lazy Sunday doing absolutely nothing together.",
  "The day we found our favorite local restaurant.",
  "That impromptu dance party in our pajamas.",
  "When we stayed up to watch a meteor shower.",
  "Our first homemade pizza night.",
  "The day we planted a tree together.",
  "That time we went berry picking.",
  "When we created our own cocktail recipe.",
  "Our first attempt at a DIY project together.",
  "The day we started our couples' journal.",
  "That sunset walk on the beach.",
  "When we planned a surprise for someone we love.",
  "Our first 'nothing special' day that felt so special.",
  "The day we created our first video compilation.",
  "That wine tasting tour we went on.",
  "When we learned a new skill together.",
  "Our first time babysitting together.",
  "The day we realized we balance each other perfectly.",
  "That time we got through a challenge together.",
  "When we set up our first home together.",
  "Our first double date with friends.",
  "The day we started our own book club of two.",
  "That time we helped each other achieve a goal.",
  "When we created a memory jar to collect moments.",
  "Our first time making breakfast together.",
  "The day we found out we have the same taste in music.",
  "That time we planned our future travels.",
  "When we celebrated an unexpected win together.",
  "Our first outdoor adventure together.",
  "The day we discovered our shared love for the same movie.",
  "That moment when we realized we were meant to be.",
  "When we looked at old photos together for the first time."
];

// Export a function to get a specific memory text by index
export const getMemoryText = (index: number): string => {
  if (index >= 1 && index <= memoryTexts.length) {
    return memoryTexts[index - 1];
  }
  return "Create a special memory description here...";
};
