// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbbwnvddulhxiefmdekk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiYndudmRkdWxoeGllZm1kZWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjU4NTUsImV4cCI6MjA2MTY0MTg1NX0.UIX9p_qgjiSSNMbtw0U4DBZM6cmz4fIY-LqumKY1R9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);